#!/bin/bash

echo "🚗 CarMax AutoCare Network - Quick Demo"
echo "======================================="
echo ""
echo "Since the React development server is having issues, here's how to access the demo:"
echo ""
echo "✅ Backend API is running at:"
echo "   http://localhost:8000/docs"
echo ""
echo "This is the Swagger UI where you can:"
echo "1. Search for repair shops"
echo "2. Get price estimates"
echo "3. Book appointments"
echo "4. View analytics dashboard data"
echo ""
echo "📊 Try these demo scenarios in the API:"
echo ""
echo "1. Shop Search:"
echo "   - Click on 'GET /api/shops/search'"
echo "   - Try it out with lat: 37.7749, lng: -122.4194 (San Francisco)"
echo "   - See the list of certified repair shops"
echo ""
echo "2. Price Estimate:"
echo "   - Click on 'POST /api/pricing/estimate'"
echo "   - Use shop_id: 'shop_001', service: 'brake-service', has_maxcare: true"
echo "   - See the MaxCare discount in action"
echo ""
echo "3. Dashboard Analytics:"
echo "   - Click on 'GET /api/analytics/dashboard'"
echo "   - View real-time metrics showing $10-15M annual savings"
echo ""
echo "Press Ctrl+C to exit"